{% set version = "1.1.0" %}

package:
  name: spglm
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/spglm/spglm-{{ version }}.tar.gz
  sha256: 20519dc38be9d660a28109bb1b89d1068454e79f6413bab2e3987db5bf959327

build:
  number: 0
  # Python 3.10 is chosen due to older versions like 3.9 dependence on libpysal 4.5.1, which in turn loads incompatible version of scipy
  skip: true  # [py<310]
  script: {{ PYTHON }} -m pip install --no-deps --no-build-isolation --ignore-installed -vv .

requirements:
  host:
    - python
    - pip
    - setuptools >=61.0
    - setuptools_scm >=6.2
    - wheel
  run:
    - python
    - libpysal >=4.10 # specific version is chosen due to older version being dependant on incompatible scipy
    - numpy >=1.3
    - scipy >=0.11
    - spreg >=1.0.4

test:
  imports:
    - spglm
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pysal/spglm
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: Sparse generalized linear models
  dev_url: https://github.com/pysal/spglm
  doc_url: https://github.com/pysal/spglm/tree/main/docs
  description: |
    This module is an adaptation of a portion of GLM functionality from the Statsmodels package, 
    this it has been simplified and customized for the purposes of serving as the base for several 
    other PySAL modules, namely SpInt and GWR.

extra:
  recipe-maintainers:
    - ocefpaf
