{% set version = "1.0.7" %}

package:
  name: spglm
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/spglm/spglm-{{ version }}.tar.gz
  sha256: 75262ae0c0583ac29b540b9e24713b722774dfd54e887e0c97d2e6c4b0f0e6f6

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - libpysal
    - numpy
    - scipy
    - spreg

test:
  imports:
    - spglm

about:
  home: https://github.com/pysal/spglm
  license: BSD-3-Clause
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: Sparse generalized linear models

extra:
  recipe-maintainers:
    - ocefpaf
