{% set version = "1.0.6" %}

package:
  name: spglm
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/spglm/spglm-{{ version }}.tar.gz
  sha256: b5e7b5e7ccdb4d0cf64ace03af28de8b4633aff42b2b86bc5e879f16c33634df

build:
  number: 1000
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - libpysal
    - numpy
    - scipy
    - spreg

test:
  imports:
    - spglm

about:
  home: https://github.com/pysal/spglm
  license: BSD-3-Clause
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: Sparse generalized linear models

extra:
  recipe-maintainers:
    - ocefpaf
