appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: cFxCtVbAoKmiDBT4DnGJMIRjJ9op9FqGsBh1CgLi1946ImuSHk2EzhTeTPjpVZurG3ueDaPdyEeicwJ401mYDdlO31klyI3UcITcGDdDumnf+Lc1LwiI5PKou+pjR/KFc9/KqsI/4QP4C/O/aN7VQXldFwsBLkm/eNaTi7oYDro/hiKTxzdbROc3QT0J75GAro13C+9HaAXWmEHmcHk2UxYF1hPkRH3tmOAHkLhEyKt94KloXIJdX1V5+2Ra1WETLDSWcTIbeY0xLm9/cUhTJaISCF3M6tyyPXBiOqWuB2KcNLyTq9Zd12IdFLas+P9ztiMQyuLvXd5r/jAcpJGigf6r2Sa7nlD2e+cQj/9EzRznwLTZPmQyxYAtmbft51WzTaFIjQg6NKKPchCk+3r6qrGr8uPibvqWOMp1MvxYb6Yi3iYdYwNVA7edn4HYG1MAra3dxXvdDHdiQf+xY4tC0aUxVLc2Qw6HoDeP+Io4koK1UuGDAZybQtJ/GgCIHXCH5LW3gKnE65GQoAg6omxceQEOGHg6qWwvuivZX4UsYJXpBCVCK6cDaAneSjT3NduPwx58oYZDRelCK0gjaabQvEChAk5xuoHsFClfoFjmT3iIEBWxNUhsq4VsYWOHAdG1fyhjxcSG+K5OfRXh3Pvu2Od9MmKIa2yLGNdTOK7d0bQ=}
conda_forge_output_validation: false
